### ISSUE TITLE
Odstrani __pycache__

### ISSUE THREAD

**Issue by andrejbauer** [MihaPac/stirivrsto#1]
Mapa `__pycache__` ne spada v repozitorij, odstranita jo.
Nato dodajta `__pycache__` v `.gitignore`, da ne bo Git
ponujal, da ga doda v repozitorij.

**Comment by MihaPac** [comment]
Spet se je znašel v datoteki __pycache__.

**Comment by andrejbauer** [comment]
Bo treba nastaviti `.gitignore`, glej [navodila](https://help.github.com/articles/ignoring-files/). Pa nehat uporabljat `git add *` in podobne zadeve, ki kar same dodajajo vse živo v repozitorij.

**Comment by andrejbauer** [comment]
V commitu 4d2b6160d352001e0386f57e858291a70678467e si dodajal datoteke v `__pycache__`. Ali si jih sploh kdaj zbrisal eksplicitno iz repozitorija? (Ko jih daš enkrat notri, jih je treba tudi pobrisati, čeprav imaš v `.gitignore` napisano, da se `__pycache__` ignorira).
